service: pydata29

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: s3:*
      Resource: arn:aws:s3:::pydata-29/*
    - Effect: Allow
      Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
      Resource: "*"

functions:
  process:
    handler: handler.process

#resources:
  #Resources:
    #ExistingResource:
      #Type: AWS::S3::Bucket
      #Properties:
        #BucketName: pydata-29
